### ISSUE TITLE
Copier Dependency Issue

### ISSUE THREAD

**Issue by smolprateek** [skit-ai/dialogy-template-simple-transformers#117]
In Dialogy 0.9.21, `dialogy create project` is showing the following error. It got fixed after doing a `pip install copier==5.1.0`. Originally, copier version 6.2.0 was installed.
```
➜ dialogy create projectname-latest
Traceback (most recent call last):
  File "/root/.pyenv/versions/project-dir/bin/dialogy", line 8, in <module>
    sys.exit(main())
  File "/root/.pyenv/versions/3.8.7/envs/project-dir/lib/python3.8/site-packages/dialogy/cli/__init__.py", line 116, in main
    project.project_cli(args)
  File "/root/.pyenv/versions/3.8.7/envs/project-dir/lib/python3.8/site-packages/dialogy/cli/project.py", line 79, in project_cli
    manage_project(
  File "/root/.pyenv/versions/3.8.7/envs/project-dir/lib/python3.8/site-packages/dialogy/cli/project.py", line 47, in manage_project
    copy(
  File "/root/.pyenv/versions/3.8.7/envs/project-dir/lib/python3.8/site-packages/copier/main.py", line 800, in run_auto
    return run_copy(src_path, dst_path, data, **kwargs)
  File "/root/.pyenv/versions/3.8.7/envs/project-dir/lib/python3.8/site-packages/copier/main.py", line 763, in run_copy
    worker = Worker(src_path=src_path, dst_path=Path(dst_path), **kwargs)
  File "pydantic/dataclasses.py", line 310, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    f'eq={self.eq!r},'
  File "pydantic/dataclasses.py", line 285, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
    # it.
TypeError: __init__() got an unexpected keyword argument 'only_diff'

**Comment by dakshvar22** [comment]
https://github.com/skit-ai/dialogy/pull/162 fixes it
